### ISSUE TITLE
Licenza

### ISSUE THREAD

**Issue by foxyseta** [MatteoDonati/unibo_artificial_intelligence_notes#1]
Ciao! Stavamo considerando di ricaricare i tuoi appunti sulle repository GitHub di https://risorse.students.cs.unibo.it.
Purtroppo stai usando la licenza MIT, che noi non usiamo per gli appunti (siccome è una licenza software), e non per gli appunti (siccome non sono software). Usiamo una Creative Commons. Potremmo caricare lo stesso?

**Comment by matteodonati** [comment]
Ciao! La licenza è stata modificata con una CC-BY-4.0, la quale presenta condizione di Attribuzione.

**Comment by foxyseta** [comment]
Perfetto, grazie. Rispetteremo di certo l'attribuzione. Per quanto mi riguarda, questa issue si può chiudere.
